### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by Zaromet** [WoWs-Builder-Team/minimap_renderer#1]
**Is your feature request related to a problem? Please describe.**
I' working on installing this on Ubuntu for hours...

**Describe the solution you'd like**
I manage to figure out how not to have error in a first step(not sure what I had to install for that but I installed a lot of things). Than I have no idea if I need to go to directory venv(got the error that I have wrong Python version(3.8.10) or don't(got the same error). I do have python 3.10.6 installed and I even run update-alternatives to set 3.10 as default. I have no idea what I need to do... I also attempted with sudo all the commands.

**Describe alternatives you've considered**
Alternative would also be links to related instructions that might be needed if you get an error or how. Another alternative would also be to have an option to have this on a private chat or different Discord server.

**Additional context**
I'm not Linux user so I have no idea where or how to find help...

**Comment by imkindaprogrammermyself** [comment]
Btw, you can you Windows if you want.

1. Install Python 3.10 (Which you've already done.)
2. Clone this repo and wait for it to finish cloning then `cd` into it. So `cd minimap_renderer` is the command.
3. Create a virtual environment. If you're using Linux, the command for creating a virtual environment is `python3.10 -m venv venv` but on Windows, you need to run this instead `py -3.10 -m venv venv`.

    - The directory that you're currently in should now contain `venv` directory.
4. Activate that virtual environment by running this command.

    - Linux: ` . venv/bin/activate`
    - Windows: `venv\Scripts\activate.bat`
    - Once activated, you should see `(venv)` at the start of the command prompt.
5. Install the package using the command `pip install -e .`
6. To renderer, use the command `render.py --replay <replay file path>

**Comment by Zaromet** [comment]
Thanks!

I was missing step 4. Thanks again for help!

Regards

**Comment by Zaromet** [comment]
Hi!

Just to let you know. You deleted this from instructions... python3.10 -m venv venv. Also for some reason I'm now getting this error.

If I use render.py --replay <replay file path>
render.py: command not found

If I use ./render.py --replay <replay file path>
bash: ./render.py: Permission denied

I guess I need another step

Regards
