### ISSUE TITLE
Show priority target count next to ship information on map

### ISSUE THREAD

**Issue by landaire** [WoWs-Builder-Team/minimap_renderer#7]
**Is your feature request related to a problem? Please describe.**

This is not related to a problem, but I think it'd be valuable to show priority target count. PT can affect decisions someone makes in a game, and it's not necessarily obvious how many folks are actively shooting at a ship.

**Describe the solution you'd like**

If a ship has priority target, show the count next to the ship's yellow detection indicator or next to where consumable locations are.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by padtrack** [comment]
this isn't possible in current game versions
